"""fix

Revision ID: 0ed240c95fb8
Revises: bfb626e5a959
Create Date: 2024-05-19 00:06:40.790203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ed240c95fb8'
down_revision: Union[str, None] = 'bfb626e5a959'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'first_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('user', 'last_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('user', 'location',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'location',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('user', 'last_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('user', 'first_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    # ### end Alembic commands ###
