"""All tables

Revision ID: 1d053247c46b
Revises: b15f47496e2e
Create Date: 2024-05-18 18:35:13.845928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d053247c46b'
down_revision: Union[str, None] = 'b15f47496e2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('current_filter', sa.JSON(), nullable=True),
    sa.Column('current_card', sa.Integer(), nullable=True),
    sa.Column('history', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('dog', 'owner_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dog', 'owner_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_table('feed')
    # ### end Alembic commands ###
