"""All tables

Revision ID: 791475bf8c87
Revises: 1d053247c46b
Create Date: 2024-05-18 18:42:10.407662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '791475bf8c87'
down_revision: Union[str, None] = '1d053247c46b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dog', sa.Column('is_premium', sa.Boolean(), nullable=True))
    # op.create_foreign_key(None, 'dog', 'user', ['is_premium'], ['is_premium'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dog', type_='foreignkey')
    op.drop_column('dog', 'is_premium')
    # ### end Alembic commands ###
