"""password

Revision ID: bfb626e5a959
Revises: 791475bf8c87
Create Date: 2024-05-19 00:04:17.211100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfb626e5a959'
down_revision: Union[str, None] = '791475bf8c87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dog', 'is_premium')
    op.drop_column('dog', 'is_visible')
    op.add_column('user', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('password_hash', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password_hash')
    op.drop_column('user', 'is_verified')
    op.add_column('dog', sa.Column('is_visible', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('dog', sa.Column('is_premium', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
