"""total_cards

Revision ID: e64118217c33
Revises: d6f2e171461c
Create Date: 2024-05-20 02:55:17.068697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e64118217c33'
down_revision: Union[str, None] = 'd6f2e171461c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feed', sa.Column('total_cards', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feed', 'total_cards')
    # ### end Alembic commands ###
